const DISPATCH_EVENTS = {
  SET_CURRENT_QUESTION_TO_STATE: 'SET CURRENT QUESTION TO STATE',
  UPDATE_CURRENT_QUESTION: 'UPDATE CURRENT QUESTION',
  CHANGE_CURRENT_QUESTION: 'CHANGE CURRENT QUESTION'
}

export default DISPATCH_EVENTS
