const TEXTINGS = {
  requiredAnswerMessage: 'The answer is required',
  submitHint: 'Press enter',
  choicePlaceholder: 'Choice',
  conditionRemovingWarn: 'This option has connected logic, delete it anyway?',
  editButton: 'Edit',
  removeButton: 'Delete',
  createForm: 'Add new form',
  uploadImage: 'Upload new image',
  uploaderHint: 'Click or drag file to this area to upload',
  itemRemovingHint: 'Delete this item?',
  questionListTitle: 'Questions',
  endingListTitle: 'Endings',
  questionCreationTooltip: 'Create new question',
  endingCreationTooltip: 'Create new ending',
  formViewTooltip: 'Form preview',
  answerViewTooltip: 'Answers preview',
  longTextHint: 'Shift ⇧ + Enter ↵ to make a line break',
  textQuestionPlaceholder: 'Type your answer here',
  listItemNoDescription: 'No description',
  popconfirmDeleteFormTitle: 'Remove form?',
  popconfirmDeleteImageTitle: 'Remove image?',
  conditionModalIsUploaded: 'is uploaded',
	conditionModalIsRecorded: 'is recorded',
  emptyDescription: 'Nothing was found',
  ratingExtendedDefaultOption: 'Extended option',
  datepickerPlaceholder: 'Select date',

  //domains: form components
  conditionsEndingsTab: 'Endings',
  conditionsLogicJumpsTab: 'Logic jumps',
  conditionsQuizTab: 'Answer score configurations',
  conditionsNoData: 'There are no question to configure',
  conditionAddQuestionType: 'Please, add one of the following questions types',
  quizSwitcherText: 'Enable quiz system',
  formTitlePlaceholder: 'Form name',
  formSubtitlePlaceholder: 'Form short description',
  formModalCreateTitle: 'Create new form',
  formModalEditTitle: 'Edit form',
  formModalEditButton: 'Save changes',
  formModalCreateButton: 'Create form',
  formValidationRule: 'Please, enter form name',

  //domains: form routes
  phoneBreakpointDummy: 'This feature is available only on desktop',
  formsAllTitle: 'Forms',
  formCounter: 'Amount of forms',
  formSearchPlaceholder: 'Search form by name',
  formDefaultWelcomeScreenTitle: 'Welcome screen',
  formDefaultEndingTitle: 'Thank you for attention!',

  //domains: condition components
  conditionsEndingSelectPlaceholder: 'Select questions to call current ending',
  conditionModalTitle: 'Logic',
  conditionModalResetLogic: 'Reset logic',
  conditionModalResetLogicButton: 'Reset',
  conditionModalSubmitButton: 'Close',
  conditionsModalTooltip: 'Configure logic jumps',
  conditionRedirectPlaceholder: 'Select redirect rule',
  conditionModalAddCondition: '+ Add condition',
  conditionTextInputPlaceholder: 'Enter value',
  conditionNextQuestionRedirect: 'Go to the next question',
  scoreWeightTitle: 'Enter score weight of answer',

  //domains: media library components
  mediaLibraryCounter: 'Amount of shown files',
  mediaLibraryButton: 'Change',
  mediaLibrarySearchPlaceholder: 'Search media file by name',
  mediaLibraryTitle: 'Media library',
  mediaLibraryBrightness: 'Brightness',
  mediaLibraryTypeError: 'is not a picture',
  mediaLibraryCancelButton: 'Cancel',
  mediaLibrarySubmitButton: 'Continue',

  //domains: question components
  questionFinishButton: 'Finish',
  questionStartButton: 'Start',
  questionVideo: 'Video question',
  questionRequiredSetting: 'Required',
  questionConfigurationTooltip: 'Configure question',
  questionTypeConfiguration: 'Question types',
  questionConfigurationTitle: 'settings',
  questionRangeBottomSetting: 'From',
  questionRangeUpperSetting: 'to',
  questionConfigurationOptions: 'Amount of options',
  questionEditableTitleHint: 'Editable question title',
  questionEditableSubtitleHint: 'Description (optional)',
  questionRemovingPopconfirm: 'Delete this question?',
  questionWithLogicRemovingPopconfirm:
    'This question has connected logic, delete it anyway?',
  questionConfigurationExtended: 'Turn on extended options',
  questionConfigurationMultiple: 'Switch to multiple option',
  questionTypeChangePopconfirm:
    'Changing the question type will delete all connected logic',

  //domains: answer components
  answerTitle: 'Answers',
  answerEmptyList: 'There is no responses yet',
  answerUserListTitle: 'Users',
  answersNoSelectedUser: 'Choose user to display their answers',
  answerTableQuestionTitle: 'Question',
  answerTableAnswerTitle: 'Answer',
  answerTableScoreTitle: 'Score'
}

export default TEXTINGS
