import React, { useEffect, useState } from 'react'
import QUESTION_TYPE, { QUESTION_TYPE_VALUE } from 'app/constants/quetstionType'
import {
  GlobalOutlined,
  HomeOutlined,
  RadiusBottomrightOutlined
} from '@ant-design/icons'
import { Box, Col, Container, Row } from '@qonsoll/react-design'
import { Card } from 'antd'
// import PropTypes from 'prop-types'
// import { useTranslation } from 'react-i18next'

/*
  [AUTOGENERATED]
  Please remove this section, if you are going to make changes
  in this file.
*/
const questionTypeMap = {
  [QUESTION_TYPE.WELCOME_SCREEN]: {
    value: QUESTION_TYPE_VALUE,
    icon: <RadiusBottomrightOutlined />
  },
  [QUESTION_TYPE.SHORT_TEXT]: {
    type: QUESTION_TYPE.SHORT_TEXT,
    icon: <HomeOutlined />
  },
  [QUESTION_TYPE.WELCOME_SCREEN]: {
    type: QUESTION_TYPE.WELCOME_SCREEN,
    icon: <GlobalOutlined />
  },
  [QUESTION_TYPE.WELCOME_SCREEN]: {
    type: QUESTION_TYPE.WELCOME_SCREEN,
    icon: <RadiusBottomrightOutlined />
  },
  [QUESTION_TYPE.WELCOME_SCREEN]: {
    type: QUESTION_TYPE.WELCOME_SCREEN,
    icon: <RadiusBottomrightOutlined />
  },
  [QUESTION_TYPE.WELCOME_SCREEN]: {
    type: QUESTION_TYPE.WELCOME_SCREEN,
    icon: <RadiusBottomrightOutlined />
  }
}

function QuestionTypeView(props) {
  // const { WRITE_PROPS_HERE } = props
  // const { ADDITIONAL_DESTRUCTURING_HERE } = user

  // [ADDITIONAL HOOKS]
  // const { t } = useTranslation('translation')
  // const { currentLanguage } = t

  // [COMPONENT STATE HOOKS]
  // const [state, setState] = useState({})

  // [COMPUTED PROPERTIES]

  // [CLEAN FUNCTIONS]

  // [USE_EFFECTS]
  useEffect(() => {
    let isComponentMounted = true

    // [EFFECT LOGIC]
    // write code here...
    // code sample: isComponentMounted && setState(<your data for state updation>)

    // [CLEAN UP FUNCTION]
    return () => {
      // [OTHER CLEAN UP-S (UNSUBSCRIPTIONS)]
      // write code here...

      // [FINAL CLEAN UP]
      isComponentMounted = false
    }
  }, [])

  return (
    <Box>
      <Row>
        <Col cw={'auto'}>
          <RadiusBottomrightOutlined />
        </Col>
        <Col>{QUESTION_TYPE.WELCOME_SCREEN}</Col>
      </Row>
    </Box>
  )
}

QuestionTypeView.propTypes = {}

export default QuestionTypeView
