import React, { useEffect, useState } from 'react'
import { Input, Typography } from 'antd'
import PropTypes from 'prop-types'

// import { useTranslation } from 'react-i18next'
const { Text } = Typography
/*
  [AUTOGENERATED]
  Please remove this section, if you are going to make changes
  in this file.
*/

function ChoiseInput(props) {
  const { index = 1, pressKey = 'N' } = props
  // const { ADDITIONAL_DESTRUCTURING_HERE } = user

  // [ADDITIONAL HOOKS]
  // const { t } = useTranslation('translation')
  // const { currentLanguage } = t

  // [COMPONENT STATE HOOKS]
  // const [state, setState] = useState({})

  // [COMPUTED PROPERTIES]

  // [CLEAN FUNCTIONS]

  // [USE_EFFECTS]
  useEffect(() => {
    let isComponentMounted = true

    // [EFFECT LOGIC]
    // write code here...
    // code sample: isComponentMounted && setState(<your data for state updation>)

    // [CLEAN UP FUNCTION]
    return () => {
      // [OTHER CLEAN UP-S (UNSUBSCRIPTIONS)]
      // write code here...

      // [FINAL CLEAN UP]
      isComponentMounted = false
    }
  }, [])

  return (
    <Input
      placeholder={`choise ${index}`}
      prefix={
        <Text
          style={{
            padding: '0 5px',
            fontSize: '12px',
            border: '1px solid lightblue'
            //marginRight: '5px'
          }}>
          {pressKey}
        </Text>
      }
      style={{ cursor: 'pointer' }}
    />
  )
}

ChoiseInput.propTypes = {}

export default ChoiseInput
