import React, { useEffect, useState } from 'react'
import { Input, Typography } from 'antd'
const { TextArea } = Input

// import PropTypes from 'prop-types'
// import { useTranslation } from 'react-i18next'

/*
  [AUTOGENERATED]
  Please remove this section, if you are going to make changes
  in this file.
*/

const CustomTextArea = (props) => {
  const {
    onSubmit,
    textAreaProps,
    btnProps,
    noBorder,
    shortText,
    btnIcon
  } = props

  useEffect(() => {
    let isComponentMounted = true

    return () => {
      isComponentMounted = false
    }
  }, [])

  return (
    <TextArea
      style={{
        paddingLeft: 0,
        borderBottom: '2px solid lightgrey',
        // lineHeight: '40px',
        fontSize: '25px'
      }}
      placeholder="Type your answer here..."
      autoSize={{ minRows: 1, maxRows: 6 }}
      bordered={!noBorder}
      btnIcon={btnIcon}
      {...textAreaProps}
      {...btnProps}
    />
  )
}

CustomTextArea.propTypes = {}

export { CustomTextArea }
