import React, { useEffect, useState } from 'react'
import { Typography } from 'antd'
// import PropTypes from 'prop-types'
// import { useTranslation } from 'react-i18next'

/*
  [AUTOGENERATED]
  Please remove this section, if you are going to make changes
  in this file.
*/

function TextEditable(props) {
  const { onChange } = props
  // const { ADDITIONAL_DESTRUCTURING_HERE } = user

  // [ADDITIONAL HOOKS]
  // const { t } = useTranslation('translation')
  // const { currentLanguage } = t

  // [COMPONENT STATE HOOKS]
  const [textValue, setTextValue] = useState()
  const [isEditing, setIsEditing] = useState(false)

  // [COMPUTED PROPERTIES]
  const editingProps = {
    onChange: setTextValue,
    icon: <></>,
    editing: isEditing,
    onEnd: () => {
      //onChange(textValue)
      setIsEditing(!isEditing)
    }
  }
  // [CLEAN FUNCTIONS]

  // [USE_EFFECTS]
  useEffect(() => {
    let isComponentMounted = true

    // [EFFECT LOGIC]
    // write code here...
    // code sample: isComponentMounted && setState(<your data for state updation>)

    // [CLEAN UP FUNCTION]
    return () => {
      // [OTHER CLEAN UP-S (UNSUBSCRIPTIONS)]
      // write code here...

      // [FINAL CLEAN UP]
      isComponentMounted = false
    }
  }, [])

  return (
    <Typography.Text
      onClick={() => {
        setIsEditing(!isEditing)
      }}
      editable={editingProps}>
      {textValue || 'click to change text'}
    </Typography.Text>
  )
}

TextEditable.propTypes = {}

export default TextEditable
